update rc.d

diff --git a/etc/rc.d/apmd b/etc/rc.d/apmd
--- a/etc/rc.d/apmd
+++ b/etc/rc.d/apmd
@@ -1,18 +1,17 @@
 #!/bin/sh
 #
-# $NetBSD: apmd,v 1.5 2002/03/22 04:33:58 thorpej Exp $
-# $FreeBSD: src/etc/rc.d/apmd,v 1.12 2004/10/07 13:55:25 mtm Exp $
 # $MidnightBSD$
+#
 
 # PROVIDE: apmd
 # REQUIRE: DAEMON apm
 # BEFORE:  LOGIN
-# KEYWORD: nojail
+# KEYWORD: nojail shutdown
 
 . /etc/rc.subr
 
 name="apmd"
-rcvar=`set_rcvar`
+rcvar="apmd_enable"
 command="/usr/sbin/${name}"
 start_precmd="apmd_prestart"
 
@@ -20,24 +19,18 @@ apmd_prestart()
 {
 	case `${SYSCTL_N} hw.machine_arch` in
 	i386)
-		# Enable apm if it is not already enabled
-		if ! checkyesno apm_enable  && \
-		    ! /etc/rc.d/apm forcestatus 1>/dev/null 2>&1
-		then
-			force_depend apm || return 1
-		fi
+		force_depend apm || return 1
 
 		# Warn user about acpi apm compatibility support which
 		# does not work with apmd.
 		if [ ! -e /dev/apmctl ]; then
-		    warn "/dev/apmctl not found; kernel is missing apm(4)"
+			warn "/dev/apmctl not found; kernel is missing apm(4)"
 		fi
 		;;
 	*)
 		return 1
 		;;
 	esac
-	return 0
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/ip6addrctl b/etc/rc.d/ip6addrctl
--- a/etc/rc.d/ip6addrctl
+++ b/etc/rc.d/ip6addrctl
@@ -1,26 +1,33 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/ip6addrctl,v 1.4 2004/10/07 13:55:26 mtm Exp $
-# $MidnightBSD: src/etc/rc.d/ip6addrctl,v 1.3 2007/10/26 14:12:39 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: ip6addrctl
-# REQUIRE: FILESYSTEMS netif
-# BEFORE: network_ipv6
+# REQUIRE: FILESYSTEMS
+# BEFORE: netif
 # KEYWORD: nojail
 
 . /etc/rc.subr
+. /etc/network.subr
 
 name="ip6addrctl"
-rcvar=`set_rcvar`
+rcvar="ip6addrctl_enable"
 start_cmd="ip6addrctl_start"
 stop_cmd="ip6addrctl_stop"
 extra_commands="status prefer_ipv6 prefer_ipv4"
 status_cmd="ip6addrctl"
 prefer_ipv6_cmd="ip6addrctl_prefer_ipv6"
 prefer_ipv4_cmd="ip6addrctl_prefer_ipv4"
+config_file="/etc/ip6addrctl.conf"
+
+set_rcvar_obsolete ipv6_enable ipv6_activate_all_interfaces
+set_rcvar_obsolete ipv6_prefer ip6addrctl_policy
 
 ip6addrctl_prefer_ipv6()
 {
+	afexists inet6 || return 0
+
 	ip6addrctl flush >/dev/null 2>&1
 	ip6addrctl add ::1/128		50	0
 	ip6addrctl add ::/0		40	1
@@ -32,6 +39,8 @@ ip6addrctl_prefer_ipv6()
 
 ip6addrctl_prefer_ipv4()
 {
+	afexists inet6 || return 0
+
 	ip6addrctl flush >/dev/null 2>&1
 	ip6addrctl add ::ffff:0:0/96	50	0
 	ip6addrctl add ::1/128		40	1
@@ -43,30 +52,50 @@ ip6addrctl_prefer_ipv4()
 
 ip6addrctl_start()
 {
-	if ifconfig lo0 inet6 >/dev/null 2>&1; then
-		# We have IPv6 support in kernel.
+	afexists inet6 || return 0
 
-		# install the policy of the address selection algorithm.
-		if [ -f /etc/ip6addrctl.conf ]; then
+	# install the policy of the address selection algorithm.
+	case "${ip6addrctl_policy}" in
+	[Aa][Uu][Tt][Oo])
+		if [ -r "${config_file}" -a -s "${config_file}" ]; then
 			ip6addrctl flush >/dev/null 2>&1
-			ip6addrctl install /etc/ip6addrctl.conf
+			ip6addrctl install "${config_file}"
 			checkyesno ip6addrctl_verbose && ip6addrctl
 		else
-			if checkyesno ipv6_enable; then
+			if checkyesno ipv6_activate_all_interfaces; then
 				ip6addrctl_prefer_ipv6
 			else
 				ip6addrctl_prefer_ipv4
 			fi
 		fi
-	fi
+	;;
+	ipv4_prefer)
+		ip6addrctl_prefer_ipv4
+	;;
+	ipv6_prefer)
+		ip6addrctl_prefer_ipv6
+	;;
+	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
+		# Backward compatibility when ipv6_prefer=YES
+		ip6addrctl_prefer_ipv6
+	;;
+	[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|[Oo][Ff][Ff]|0)
+		# Backward compatibility when ipv6_prefer=NO
+		ip6addrctl_prefer_ipv4
+	;;
+	*)
+		warn "\$ip6addrctl_policy is invalid: ${ip6addrctl_policy}. " \
+		    " \"ipv4_prefer\" is used instead."
+		ip6addrctl_prefer_ipv4
+	;;
+	esac
 }
 
 ip6addrctl_stop()
 {
-	if ifconfig lo0 inet6 >/dev/null 2>&1; then
-		# We have IPv6 support in kernel.
-		ip6addrctl flush >/dev/null 2>&1
-	fi
+	afexists inet6 || return 0
+
+	ip6addrctl flush >/dev/null 2>&1
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/ipfw b/etc/rc.d/ipfw
--- a/etc/rc.d/ipfw
+++ b/etc/rc.d/ipfw
@@ -1,11 +1,10 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/ipfw,v 1.15 2007/04/02 15:38:53 mtm Exp $
-# $MidnightBSD: src/etc/rc.d/ipfw,v 1.5 2007/10/26 14:12:39 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: ipfw
 # REQUIRE: ppp
-# BEFORE: NETWORKING
 # KEYWORD: nojail
 
 . /etc/rc.subr
@@ -14,19 +13,37 @@
 name="ipfw"
 rcvar="firewall_enable"
 start_cmd="ipfw_start"
+start_precmd="ipfw_prestart"
+start_postcmd="ipfw_poststart"
 stop_cmd="ipfw_stop"
 required_modules="ipfw"
 
+set_rcvar_obsolete ipv6_firewall_enable
+
+ipfw_prestart()
+{
+	if checkyesno dummynet_enable; then
+		required_modules="$required_modules dummynet"
+	fi
+
+	if checkyesno firewall_nat_enable; then
+		if ! checkyesno natd_enable; then
+			required_modules="$required_modules ipfw_nat"
+		fi
+	fi
+}
+
 ipfw_start()
 {
+	local   _firewall_type
+
+	_firewall_type=$1
+
 	# set the firewall rules script if none was specified
 	[ -z "${firewall_script}" ] && firewall_script=/etc/rc.firewall
 
 	if [ -r "${firewall_script}" ]; then
-		if [ -f /etc/rc.d/natd ] ; then
-			/etc/rc.d/natd start
-		fi
-		/bin/sh "${firewall_script}"
+		/bin/sh "${firewall_script}" "${_firewall_type}"
 		echo 'Firewall rules loaded.'
 	elif [ "`ipfw list 65535`" = "65535 deny ip from any to any" ]; then
 		echo 'Warning: kernel has firewall functionality, but' \
@@ -40,21 +57,54 @@ ipfw_start()
 		echo 'Firewall logging enabled.'
 		sysctl net.inet.ip.fw.verbose=1 >/dev/null
 	fi
+}
+
+ipfw_poststart()
+{
+	local	_coscript
+
+	# Start firewall coscripts
+	#
+	for _coscript in ${firewall_coscripts} ; do
+		if [ -f "${_coscript}" ]; then
+			${_coscript} quietstart
+		fi
+	done
 
 	# Enable the firewall
 	#
-	${SYSCTL_W} net.inet.ip.fw.enable=1
+	if ! ${SYSCTL} net.inet.ip.fw.enable=1 1>/dev/null 2>&1; then
+		warn "failed to enable IPv4 firewall"
+	fi
+	if afexists inet6; then
+		if ! ${SYSCTL} net.inet6.ip6.fw.enable=1 1>/dev/null 2>&1
+		then
+			warn "failed to enable IPv6 firewall"
+		fi
+	fi
 }
 
 ipfw_stop()
 {
+	local	_coscript
+
 	# Disable the firewall
 	#
-	${SYSCTL_W} net.inet.ip.fw.enable=0
-	if [ -f /etc/rc.d/natd ] ; then
-		/etc/rc.d/natd stop
+	${SYSCTL} net.inet.ip.fw.enable=0
+	if afexists inet6; then
+		${SYSCTL} net.inet6.ip6.fw.enable=0
 	fi
+
+	# Stop firewall coscripts
+	#
+	for _coscript in `reverse_list ${firewall_coscripts}` ; do
+		if [ -f "${_coscript}" ]; then
+			${_coscript} quietstop
+		fi
+	done
 }
 
 load_rc_config $name
-run_rc_command "$1"
+firewall_coscripts="/etc/rc.d/natd ${firewall_coscripts}"
+
+run_rc_command $*
diff --git a/etc/rc.d/mountd b/etc/rc.d/mountd
--- a/etc/rc.d/mountd
+++ b/etc/rc.d/mountd
@@ -1,16 +1,16 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/mountd,v 1.19.4.1 2008/01/28 07:58:31 dougb Exp $
-# $MidnightBSD: src/etc/rc.d/mountd,v 1.2 2006/08/28 02:47:45 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: mountd
-# REQUIRE: NETWORKING nfsserver rpcbind quota
-# KEYWORD: nojail
+# REQUIRE: NETWORKING rpcbind quota
+# KEYWORD: nojail shutdown
 
 . /etc/rc.subr
 
 name="mountd"
-rcvar=`set_rcvar`
+rcvar="mountd_enable"
 command="/usr/sbin/${name}"
 pidfile="/var/run/${name}.pid"
 required_files="/etc/exports"
@@ -19,11 +19,7 @@ extra_commands="reload"
 
 mountd_precmd()
 {
-	if ! checkyesno rpcbind_enable  && \
-	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
-	then
-		force_depend rpcbind || return 1
-	fi
+	force_depend rpcbind || return 1
 
 	# mountd flags will differ depending on rc.conf settings
 	#
@@ -37,13 +33,19 @@ mountd_precmd()
 		fi
 	fi
 
+	# If oldnfs_server_enable is yes, force use of the old NFS server
+	#
+	if checkyesno oldnfs_server_enable; then
+		rc_flags="-o ${rc_flags}"
+	fi
+
 	if checkyesno zfs_enable; then
 		rc_flags="${rc_flags} /etc/exports /etc/zfs/exports"
 	fi
 
 	rm -f /var/db/mountdtab
-	( umask 022 ; > /var/db/mountdtab )
-	return 0
+	( umask 022 ; > /var/db/mountdtab ) ||
+	    err 1 'Cannot create /var/db/mountdtab'
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/nfsclient b/etc/rc.d/nfsclient
--- a/etc/rc.d/nfsclient
+++ b/etc/rc.d/nfsclient
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/nfsclient,v 1.6 2006/12/31 10:37:18 yar Exp $
-# $MidnightBSD: src/etc/rc.d/nfsclient,v 1.2 2006/08/28 02:47:46 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: nfsclient
 # REQUIRE: NETWORKING mountcritremote rpcbind
@@ -13,7 +13,7 @@ name="nfsclient"
 rcvar="nfs_client_enable"
 start_cmd="nfsclient_start"
 stop_cmd="unmount_all"
-required_modules="nfsclient:nfs"
+required_modules="nfscl:nfs"
 
 nfsclient_start()
 {
@@ -22,11 +22,16 @@ nfsclient_start()
 	#
 
 	if [ -n "${nfs_access_cache}" ]; then
-		echo "NFS access cache time=${nfs_access_cache}"
-		sysctl vfs.nfs.access_cache_timeout=${nfs_access_cache} >/dev/null
+		check_startmsgs &&
+			echo "NFS access cache time=${nfs_access_cache}"
+		if ! sysctl vfs.nfs.access_cache_timeout=${nfs_access_cache} >/dev/null; then
+			warn "failed to set access cache timeout"
+		fi
 	fi
 	if [ -n "${nfs_bufpackets}" ]; then
-		 sysctl vfs.nfs.bufpackets=${nfs_bufpackets} > /dev/null
+		if ! sysctl vfs.nfs.bufpackets=${nfs_bufpackets} > /dev/null; then
+			warn "failed to set vfs.nfs.bufpackets"
+		fi
 	fi
 
 	unmount_all
diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -1,46 +1,62 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/nfsd,v 1.13 2004/10/07 13:55:26 mtm Exp $
-# $MidnightBSD: src/etc/rc.d/nfsd,v 1.2 2006/08/28 02:47:46 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: nfsd
-# REQUIRE: mountd
+# REQUIRE: mountd hostname gssd nfsuserd
 # KEYWORD: nojail shutdown
 
 . /etc/rc.subr
 
 name="nfsd"
-rcvar=`set_rcvar nfs_server`
+rcvar="nfs_server_enable"
 command="/usr/sbin/${name}"
 
 load_rc_config $name
-command_args="${nfs_server_flags}"
 start_precmd="nfsd_precmd"
 sig_stop="USR1"
 
 nfsd_precmd()
 {
-	if ! sysctl vfs.nfsrv >/dev/null 2>&1; then
-		force_depend nfsserver || return 1
+	if checkyesno oldnfs_server_enable; then
+		rc_flags="-o ${nfs_server_flags}"
+
+		# Load the module now, so that the vfs.nfsrv sysctl
+		# oids are available.
+		load_kld nfsserver
+
+		if checkyesno nfs_reserved_port_only; then
+			echo 'NFS on reserved port only=YES'
+			sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
+		else
+			sysctl vfs.nfsrv.nfs_privport=0 > /dev/null
+		fi
+	else
+		rc_flags="${nfs_server_flags}"
+
+		# Load the modules now, so that the vfs.nfsd sysctl
+		# oids are available.
+		load_kld nfsd
+
+		if checkyesno nfs_reserved_port_only; then
+			echo 'NFS on reserved port only=YES'
+			sysctl vfs.nfsd.nfs_privport=1 > /dev/null
+		else
+			sysctl vfs.nfsd.nfs_privport=0 > /dev/null
+		fi
+
+		if checkyesno nfsv4_server_enable; then
+			sysctl vfs.nfsd.server_max_nfsvers=4 > /dev/null
+			force_depend nfsuserd || err 1 "Cannot run nfsuserd"
+		else
+			echo 'NFSv4 is disabled'
+			sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
+		fi
 	fi
 
-	if ! checkyesno rpcbind_enable  && \
-	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
-	then
-		force_depend rpcbind || return 1
-	fi
-
-	if ! checkyesno mountd_enable  && \
-	    ! /etc/rc.d/mountd forcestatus 1>/dev/null 2>&1
-	then
-		force_depend mountd || return 1
-	fi
-
-	if checkyesno nfs_reserved_port_only; then
-		echo 'NFS on reserved port only=YES'
-		sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
-	fi
-	return 0
+	force_depend rpcbind || return 1
+	force_depend mountd || return 1
 }
 
 run_rc_command "$1"
diff --git a/etc/rc.d/power_profile b/etc/rc.d/power_profile
--- a/etc/rc.d/power_profile
+++ b/etc/rc.d/power_profile
@@ -5,8 +5,7 @@
 #
 # Arguments: 0x00 (AC offline, economy) or 0x01 (AC online, performance)
 #
-# $MidnightBSD: src/etc/rc.d/power_profile,v 1.3 2007/10/26 15:20:25 laffer1 Exp $
-# $FreeBSD: src/etc/rc.d/power_profile,v 1.7.2.1 2005/12/15 16:47:06 obrien Exp $
+# $MidnightBSD$
 #
 
 # PROVIDE: power_profile
@@ -51,7 +50,11 @@ sysctl_set ()
 	esac
 
 	# Set the desired value
-	[ -n "${value}" ] && sysctl ${node}=${value}
+	if [ -n "${value}" ]; then
+		if ! sysctl ${node}=${value} > /dev/null 2>&1; then
+			warn "unable to set ${node}=${value}"
+		fi
+	fi
 }
 
 if [ $# -ne 1 ]; then
diff --git a/etc/rc.d/sysctl b/etc/rc.d/sysctl
--- a/etc/rc.d/sysctl
+++ b/etc/rc.d/sysctl
@@ -1,11 +1,9 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/sysctl,v 1.16 2004/10/07 13:55:26 mtm Exp $
-# $MidnightBSD: src/etc/rc.d/sysctl,v 1.3 2007/09/28 22:17:23 laffer1 Exp $
+# $MidnightBSD$
+#
 
 # PROVIDE: sysctl
-# REQUIRE: root
-# BEFORE:  DAEMON
 
 . /etc/rc.subr
 
@@ -16,12 +14,12 @@ reload_cmd="sysctl_start"
 lastload_cmd="sysctl_start last"
 extra_commands="reload lastload"
 
-sysctl_start()
+#
+# Read in a file containing sysctl settings and set things accordingly.
+#
+parse_file()
 {
-	#
-	# Read in /etc/sysctl.conf and set things accordingly
-	#
-	if [ -f /etc/sysctl.conf ]; then
+	if [ -f $1 ]; then
 		while read var comments
 		do
 			case ${var} in
@@ -36,16 +34,25 @@ sysctl_start()
 					${val})
 						;;
 					*)
-						sysctl "${var}"
+						if ! sysctl "${var}" >/dev/null 2>&1; then
+							warn "unable to set ${var}"
+						fi
 						;;
 					esac
-				elif [ "$1" = "last" ]; then
+				elif [ "$2" = "last" ]; then
 					warn "sysctl ${mib} does not exist."
 				fi
 				;;
 			esac
-		done < /etc/sysctl.conf
+		done < $1
 	fi
+}
+
+sysctl_start()
+{
+
+	parse_file /etc/sysctl.conf $1
+	parse_file /etc/sysctl.conf.local $1
 }
 
 load_rc_config $name
