FreeBSD 9.1 release

diff --git a/etc/rc.d/apmd b/etc/rc.d/apmd
--- a/etc/rc.d/apmd
+++ b/etc/rc.d/apmd
@@ -1,17 +1,17 @@
 #!/bin/sh
 #
-# $FreeBSD: release/7.0.0/etc/rc.d/apmd 175737 2008-01-28 07:58:32Z dougb $
+# $FreeBSD$
 #
 
 # PROVIDE: apmd
 # REQUIRE: DAEMON apm
 # BEFORE:  LOGIN
-# KEYWORD: nojail
+# KEYWORD: nojail shutdown
 
 . /etc/rc.subr
 
 name="apmd"
-rcvar=`set_rcvar`
+rcvar="apmd_enable"
 command="/usr/sbin/${name}"
 start_precmd="apmd_prestart"
 
@@ -19,24 +19,18 @@ apmd_prestart()
 {
 	case `${SYSCTL_N} hw.machine_arch` in
 	i386)
-		# Enable apm if it is not already enabled
-		if ! checkyesno apm_enable  && \
-		    ! /etc/rc.d/apm forcestatus 1>/dev/null 2>&1
-		then
-			force_depend apm || return 1
-		fi
+		force_depend apm || return 1
 
 		# Warn user about acpi apm compatibility support which
 		# does not work with apmd.
 		if [ ! -e /dev/apmctl ]; then
-		    warn "/dev/apmctl not found; kernel is missing apm(4)"
+			warn "/dev/apmctl not found; kernel is missing apm(4)"
 		fi
 		;;
 	*)
 		return 1
 		;;
 	esac
-	return 0
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/power_profile b/etc/rc.d/power_profile
--- a/etc/rc.d/power_profile
+++ b/etc/rc.d/power_profile
@@ -5,7 +5,7 @@
 #
 # Arguments: 0x00 (AC offline, economy) or 0x01 (AC online, performance)
 #
-# $FreeBSD: release/7.0.0/etc/rc.d/power_profile 175783 2008-01-29 00:22:33Z dougb $
+# $FreeBSD$
 #
 
 # PROVIDE: power_profile
@@ -50,7 +50,11 @@ sysctl_set ()
 	esac
 
 	# Set the desired value
-	[ -n "${value}" ] && sysctl ${node}=${value}
+	if [ -n "${value}" ]; then
+		if ! sysctl ${node}=${value} > /dev/null 2>&1; then
+			warn "unable to set ${node}=${value}"
+		fi
+	fi
 }
 
 if [ $# -ne 1 ]; then
