FreeBSD 11 stable 6ebace841cdae274f1dcecf4eefa6b9cc2a8a469 May 2020, around 11.4 release.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: release/10.0.0/etc/rc.d/fsck 252310 2013-06-27 18:28:45Z hrs $
+# $FreeBSD$
 #
 
 # PROVIDE: fsck
@@ -10,6 +10,7 @@
 . /etc/rc.subr
 
 name="fsck"
+desc="Run file system checks"
 start_cmd="fsck_start"
 stop_cmd=":"
 
@@ -20,7 +21,7 @@ fsck_start()
 	elif [ ! -r /etc/fstab ]; then
 		echo "Warning! No /etc/fstab: skipping disk checks."
 	elif [ "$autoboot" = yes ]; then
-					# During fsck ignore SIGQUIT
+		# During fsck ignore SIGQUIT
 		trap : 3
 
 		check_startmsgs && echo "Starting file system checks:"
@@ -30,7 +31,21 @@ fsck_start()
 			fsck -p
 		fi
 
-		case $? in
+		err=$?
+		if [ ${err} -eq 3 ]; then
+			echo "Warning! Some of the devices might not be" \
+			    "available; retrying"
+			root_hold_wait
+			check_startmsgs && echo "Restarting file system checks:"
+			if checkyesno background_fsck; then
+				fsck -F -p
+			else
+				fsck -p
+			fi
+			err=$?
+		fi
+
+		case ${err} in
 		0)
 			;;
 		2)
@@ -42,7 +57,7 @@ fsck_start()
 			echo "Reboot failed; help!"
 			stop_boot
 			;;
-		8)
+		8|16)
 			if checkyesno fsck_y_enable; then
 				echo "File system preen failed, trying fsck -y ${fsck_y_flags}"
 				fsck -y ${fsck_y_flags}
@@ -67,7 +82,7 @@ fsck_start()
 			stop_boot
 			;;
 		*)
-			echo "Unknown error; help!"
+			echo "Unknown error ${err}; help!"
 			stop_boot
 			;;
 		esac
diff --git a/etc/rc.d/hostid_save b/etc/rc.d/hostid_save
--- a/etc/rc.d/hostid_save
+++ b/etc/rc.d/hostid_save
@@ -1,26 +1,34 @@
 #!/bin/sh
 #
-# $FreeBSD: release/10.0.0/etc/rc.d/hostid_save 208307 2010-05-19 19:03:19Z dougb $
+# $FreeBSD$
 #
 
 # PROVIDE: hostid_save
-# REQUIRE: root
+# REQUIRE: hostid root
 # KEYWORD: nojail
 
 . /etc/rc.subr
 
 name="hostid_save"
+desc="Save unique host ID to disk"
 start_cmd="hostid_save"
 stop_cmd=":"
 rcvar="hostid_enable"
 
 hostid_save()
 {
-	if [ ! -r ${hostid_file} ]; then
-		$SYSCTL_N kern.hostuuid > ${hostid_file}
-		if [ $? -ne 0 ]; then
-			warn "could not store hostuuid in ${hostid_file}."
+	current_hostid=`$SYSCTL_N kern.hostuuid`
+
+	if [ -r ${hostid_file} ]; then
+		read saved_hostid < ${hostid_file}
+		if [ ${saved_hostid} = ${current_hostid} ]; then
+			exit 0
 		fi
+	fi
+
+	echo ${current_hostid} > ${hostid_file}
+	if [ $? -ne 0 ]; then
+		warn "could not store hostuuid in ${hostid_file}."
 	fi
 }
 
