update some of the rc scripts.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $MidnightBSD$
+# $FreeBSD: stable/11/etc/rc.d/fsck 331216 2018-03-19 17:37:51Z dab $
 #
 
 # PROVIDE: fsck
@@ -10,6 +10,7 @@
 . /etc/rc.subr
 
 name="fsck"
+desc="Run file system checks"
 start_cmd="fsck_start"
 stop_cmd=":"
 
@@ -30,7 +31,21 @@ fsck_start()
 			fsck -p
 		fi
 
-		case $? in
+		err=$?
+		if [ ${err} -eq 3 ]; then
+			echo "Warning! Some of the devices might not be" \
+			    "available; retrying"
+			root_hold_wait
+			check_startmsgs && echo "Restarting file system checks:"
+			if checkyesno background_fsck; then
+				fsck -F -p
+			else
+				fsck -p
+			fi
+			err=$?
+		fi
+
+		case ${err} in
 		0)
 			;;
 		2)
@@ -67,7 +82,7 @@ fsck_start()
 			stop_boot
 			;;
 		*)
-			echo "Unknown error; help!"
+			echo "Unknown error ${err}; help!"
 			stop_boot
 			;;
 		esac
diff --git a/etc/rc.d/hostid_save b/etc/rc.d/hostid_save
--- a/etc/rc.d/hostid_save
+++ b/etc/rc.d/hostid_save
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $MidnightBSD$
+# $FreeBSD: stable/11/etc/rc.d/hostid_save 299844 2016-05-15 06:00:13Z ngie $
 #
 
 # PROVIDE: hostid_save
@@ -10,17 +10,25 @@
 . /etc/rc.subr
 
 name="hostid_save"
+desc="Save unique host ID to disk"
 start_cmd="hostid_save"
 stop_cmd=":"
 rcvar="hostid_enable"
 
 hostid_save()
 {
-	if [ ! -r ${hostid_file} ]; then
-		$SYSCTL_N kern.hostuuid > ${hostid_file}
-		if [ $? -ne 0 ]; then
-			warn "could not store hostuuid in ${hostid_file}."
+	current_hostid=`$SYSCTL_N kern.hostuuid`
+
+	if [ -r ${hostid_file} ]; then
+		read saved_hostid < ${hostid_file}
+		if [ ${saved_hostid} = ${current_hostid} ]; then
+			exit 0
 		fi
+	fi
+
+	echo ${current_hostid} > ${hostid_file}
+	if [ $? -ne 0 ]; then
+		warn "could not store hostuuid in ${hostid_file}."
 	fi
 }
 
