merge rc changes

diff --git a/etc/rc.d/ipfilter b/etc/rc.d/ipfilter
--- a/etc/rc.d/ipfilter
+++ b/etc/rc.d/ipfilter
@@ -1,8 +1,7 @@
 #!/bin/sh
 #
-# $NetBSD: ipfilter,v 1.10 2001/02/28 17:03:50 lukem Exp $
-# $FreeBSD: src/etc/rc.d/ipfilter,v 1.24 2005/07/07 05:59:44 jkim Exp $
-# $MidnightBSD: src/etc/rc.d/ipfilter,v 1.2 2006/08/28 02:47:45 laffer1 Exp $
+# $FreeBSD: src/etc/rc.d/ipfilter,v 1.28.4.1 2008/01/28 07:58:31 dougb Exp $
+# $MidnightBSD: src/etc/rc.d/ipfilter,v 1.3 2007/10/26 14:12:39 laffer1 Exp $
 
 # PROVIDE: ipfilter
 # REQUIRE: FILESYSTEMS
@@ -16,7 +15,7 @@ rcvar=`set_rcvar`
 load_rc_config $name
 stop_precmd="test -f ${ipfilter_rules} -o -f ${ipv6_ipfilter_rules}"
 
-start_precmd="ipfilter_prestart"
+start_precmd="$stop_precmd"
 start_cmd="ipfilter_start"
 stop_cmd="ipfilter_stop"
 reload_precmd="$stop_precmd"
@@ -26,35 +25,7 @@ resync_cmd="ipfilter_resync"
 status_precmd="$stop_precmd"
 status_cmd="ipfilter_status"
 extra_commands="reload resync status"
-
-ipfilter_loaded()
-{
-	if ! kldstat -v | grep "ipfilter$" > /dev/null 2>&1; then
-		return 1
-	else
-		return 0
-	fi
-}
-
-ipfilter_prestart()
-{
-	# load ipfilter kernel module if needed
-	if ! ipfilter_loaded; then
-		if kldload ipl; then
-			info 'IP-filter module loaded.'
-		else
-			err 1 'IP-filter module failed to load.'
-		fi
-	fi
-
-	# check for ipfilter rules
-	if [ ! -r "${ipfilter_rules}" ] && [ ! -r "${ipv6_ipfilter_rules}" ]
-	then
-		warn 'IP-filter: NO IPF RULES'
-		return 1
-	fi
-	return 0
-}
+required_modules="ipl:ipfilter"
 
 ipfilter_start()
 {
@@ -93,11 +64,17 @@ ipfilter_reload()
 	if [ -r "${ipfilter_rules}" ]; then
 		${ipfilter_program:-/sbin/ipf} -I \
 		    -f "${ipfilter_rules}" ${ipfilter_flags}
+		if [ $? -ne 0 ]; then
+			err 1 'Load of rules into alternate set failed; aborting reload'
+		fi
 	fi
 	${ipfilter_program:-/sbin/ipf} -I -6 -Fa
 	if [ -r "${ipv6_ipfilter_rules}" ]; then
 		${ipfilter_program:-/sbin/ipf} -I -6 \
 		    -f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
+		if [ $? -ne 0 ]; then
+			err 1 'Load of IPv6 rules into alternate set failed; aborting reload'
+		fi
 	fi
 	${ipfilter_program:-/sbin/ipf} -s
 
@@ -105,10 +82,6 @@ ipfilter_reload()
 
 ipfilter_resync()
 {
-	# Don't resync if ipfilter is not loaded
-	if ! ipfilter_loaded; then
-		 return
-	fi
 	${ipfilter_program:-/sbin/ipf} -y ${ipfilter_flags}
 }
 
