freebsd 7.0 release

diff --git a/etc/rc.d/pflog b/etc/rc.d/pflog
--- a/etc/rc.d/pflog
+++ b/etc/rc.d/pflog
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/pflog,v 1.5.2.1 2006/01/22 13:40:47 yar Exp $
+# $FreeBSD: release/7.0.0/etc/rc.d/pflog 168531 2007-04-09 08:53:40Z des $
 #
 
 # PROVIDE: pflog
-# REQUIRE: root mountcritlocal netif cleanvar
+# REQUIRE: FILESYSTEMS netif cleanvar
 # KEYWORD: nojail
 
 . /etc/rc.subr
@@ -22,19 +22,11 @@ resync_cmd="pflog_resync"
 
 pflog_prestart()
 {
-	# load pflog kernel module if needed
-	if ! kldstat -q -m pflog; then
-		if kldload pf; then
-			info 'pf module loaded.'
-		else
-			warn 'pf module failed to load.'
-			return 1
-		fi
-	fi
+	load_kld pflog || return 1
 
 	# set pflog0 interface to up state
 	if ! ifconfig pflog0 up; then
-		warn 'could not not bring up pflog0.'
+		warn 'could not bring up pflog0.'
 		return 1
 	fi
 
