the new world order

diff --git a/sbin/dhclient/dhclient-script b/sbin/dhclient/dhclient-script
--- a/sbin/dhclient/dhclient-script
+++ b/sbin/dhclient/dhclient-script
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # $OpenBSD: dhclient-script,v 1.6 2004/05/06 18:22:41 claudio Exp $
-# $FreeBSD: src/sbin/dhclient/dhclient-script,v 1.17 2007/07/03 17:49:32 thompsa Exp $
+# $MidnightBSD$
 #
 # Copyright (c) 2003 Kenneth R Westerback <krw@openbsd.org>
 #
@@ -20,10 +20,8 @@
 #
 
 ARP=/usr/sbin/arp
-AWK=/usr/bin/awk
 HOSTNAME=/bin/hostname
 IFCONFIG='/sbin/ifconfig -n'
-NETSTAT=/usr/bin/netstat
 
 LOCALHOST=127.0.0.1
 
@@ -124,11 +122,12 @@ delete_old_routes() {
 		return 0;
 	fi
 
-	for router in $old_routers; do
-		if [ $if_defaultroute = x -o $if_defaultroute = $interface ]; then
-			route delete default $route >/dev/null 2>&1
-		fi
-	done
+	# If we supported multiple default routes, we'd be removing each
+	# one here.  We don't so just delete the default route if it's
+	# through our interface.
+	if is_default_interface; then
+		route delete default >/dev/null 2>&1
+	fi
 
 	if [ -n "$old_static_routes" ]; then
 		set $old_static_routes
@@ -169,10 +168,13 @@ add_new_routes() {
 	fi
 
 	for router in $new_routers; do
-		if [ "$new_ip_address" = "$router" ]; then
-			route add default -iface $router >/dev/null 2>&1
-		else
-			route add default $router >/dev/null 2>&1
+		if is_default_interface; then
+
+			if [ "$new_ip_address" = "$router" ]; then
+				route add default -iface $router >/dev/null 2>&1
+			else
+				route add default $router >/dev/null 2>&1
+			fi
 		fi
 		# 2nd and subsequent default routers error out, so explicitly
 		# stop processing the list after the first one.
@@ -199,7 +201,9 @@ add_new_resolv_conf() {
 	local tmpres=/var/run/resolv.conf.${interface}
 	rm -f $tmpres
 
-	if [ -n "$new_domain_name" ]; then
+	if [ -n "$new_domain_search" ]; then
+		echo "search $new_domain_search" >>$tmpres
+	elif [ -n "$new_domain_name" ]; then
 		echo "search $new_domain_name" >>$tmpres
 	fi
 
@@ -214,29 +218,40 @@ add_new_resolv_conf() {
 			cat /etc/resolv.conf.tail >>$tmpres
 		fi
 
-		# When resolv.conf is not changed actually, we don't
-		# need to update it.
-		# If /usr is not mounted yet, we cannot use cmp, then
-		# the following test fails.  In such case, we simply
-		# ignore an error and do update resolv.conf.
-		if cmp -s $tmpres /etc/resolv.conf; then
-			rm -f $tmpres
-			return 0
-		fi 2>/dev/null
+		case $resolvconf_enable in
+		# "no", "false", "off", or "0"
+		[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|[Oo][Ff][Ff]|0)
+			# When resolv.conf is not changed actually, we don't
+			# need to update it.
+			# If /usr is not mounted yet, we cannot use cmp, then
+			# the following test fails.  In such case, we simply
+			# ignore an error and do update resolv.conf.
+			if cmp -s $tmpres /etc/resolv.conf; then
+				rm -f $tmpres
+				return 0
+			fi 2>/dev/null
 
-		# In case (e.g. during OpenBSD installs) /etc/resolv.conf
-		# is a symbolic link, take care to preserve the link and write
-		# the new data in the correct location.
+			# In case (e.g. during OpenBSD installs)
+			# /etc/resolv.conf is a symbolic link, take
+			# care to preserve the link and write the new
+			# data in the correct location.
 
-		if [ -f /etc/resolv.conf ]; then
-			cat /etc/resolv.conf > /etc/resolv.conf.save
-		fi
-		cat $tmpres > /etc/resolv.conf
+			if [ -f /etc/resolv.conf ]; then
+				cat /etc/resolv.conf > /etc/resolv.conf.save
+			fi
+			cat $tmpres > /etc/resolv.conf
+
+			# Try to ensure correct ownership and permissions.
+			chown -RL root:wheel /etc/resolv.conf
+			chmod -RL 644 /etc/resolv.conf
+			;;
+
+		*)
+			/sbin/resolvconf -a ${interface} < $tmpres
+			;;
+		esac
+
 		rm -f $tmpres
-
-		# Try to ensure correct ownership and permissions.
-		chown -RL root:wheel /etc/resolv.conf
-		chmod -RL 644 /etc/resolv.conf
 
 		return 0
 	fi
@@ -254,6 +269,31 @@ exit_with_hooks() {
 	exit $exit_status
 }
 
+# Get the interface with the current ipv4 default route on it using only
+# commands that are available prior to /usr being mounted.
+is_default_interface()
+{
+	routeget="`route -n get -inet default`"
+	oldifs="$IFS"
+	IFS="
+"
+	defif=
+	for line in $routeget ; do
+		case $line in
+		*interface:*)
+			defif=${line##*: }
+			;;
+		esac
+	done
+	IFS=${oldifs}
+
+	if [ -z "$defif" -o "$defif" = "$interface" ]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
 #
 # Start of active code.
 #
@@ -269,11 +309,7 @@ if [ -f /etc/dhclient-enter-hooks ]; then
 	fi
 fi
 
-if [ -x $NETSTAT ]; then
-	if_defaultroute=`$NETSTAT -rnf inet | $AWK '{if ($1=="default") printf $6}'`
-else
-	if_defaultroute="x"
-fi
+: ${resolvconf_enable="YES"}
 
 case $reason in
 MEDIUM)
@@ -284,7 +320,7 @@ MEDIUM)
 
 PREINIT)
 	delete_old_alias
-	$IFCONFIG $interface inet 0.0.0.0 netmask 0.0.0.0 broadcast 255.255.255.255 up
+	$IFCONFIG $interface inet alias 0.0.0.0 netmask 255.0.0.0 broadcast 255.255.255.255 up
 	;;
 
 ARPCHECK|ARPSEND)
@@ -311,7 +347,9 @@ BOUND|RENEW|REBIND|REBOOT)
 	if [ "$new_ip_address" != "$alias_ip_address" ]; then
 		add_new_alias
 	fi
-	add_new_resolv_conf
+	if is_default_interface; then
+		add_new_resolv_conf
+	fi
 	;;
 
 EXPIRE|FAIL)
@@ -325,8 +363,18 @@ EXPIRE|FAIL)
 	fi
 	# XXX Why add alias we just deleted above?
 	add_new_alias
-	if [ -f /etc/resolv.conf.save ]; then
-		cat /etc/resolv.conf.save > /etc/resolv.conf
+	if is_default_interface; then
+		case $resolvconf_enable in
+		# "no", "false", "off", or "0"
+		[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|[Oo][Ff][Ff]|0)
+			if [ -f /etc/resolv.conf.save ]; then
+				cat /etc/resolv.conf.save > /etc/resolv.conf
+			fi
+			;;
+		*)
+			/sbin/resolvconf -d ${interface}
+			;;
+		esac
 	fi
 	;;
 
@@ -342,6 +390,9 @@ TIMEOUT)
 				add_new_alias
 			fi
 			add_new_routes
+			if ! is_default_interface; then
+				exit_with_hooks 0
+			fi
 			if add_new_resolv_conf; then
 				exit_with_hooks 0
 			fi
