firstboot: harden GPU installer flow
AI-Assisted-by: GPT 5.4
Signed-off-by: Lucas Holt <luke@foolishgames.com>

diff --git a/libexec/rc/rc.d/firstboot b/libexec/rc/rc.d/firstboot
--- a/libexec/rc/rc.d/firstboot
+++ b/libexec/rc/rc.d/firstboot
@@ -10,6 +10,51 @@ name="firstboot"
 rcvar=
 start_cmd="firstboot_start"
 
+warn_msg()
+{
+	echo "Warning: $*"
+}
+
+run_step()
+{
+	local description
+
+	description="$1"
+	shift
+
+	if ! "$@"; then
+		warn_msg "${description} failed."
+		return 1
+	fi
+
+	return 0
+}
+
+install_pkg()
+{
+	local pkg
+	local rc
+
+	pkg="$1"
+	rc=0
+
+	if ! /sbin/ipfw disable firewall; then
+		warn_msg "Could not disable the firewall before installing ${pkg}."
+	fi
+
+	if ! /usr/sbin/mport install "${pkg}"; then
+		warn_msg "Package installation failed for ${pkg}."
+		rc=1
+	fi
+
+	if ! /sbin/ipfw enable firewall; then
+		warn_msg "Could not re-enable the firewall after installing ${pkg}."
+		rc=1
+	fi
+
+	return ${rc}
+}
+
 firstboot_start()
 {
 	local lsuffix
@@ -24,117 +69,142 @@ firstboot_start()
 
 	if [ ! -f ${receipt} ]; then
 		echo -e "\r${red}MidnightBSD FirstBoot Configuration${lsuffix}"
-		echo "This utility requires an active Internet connection."
+			echo "This utility requires an active Internet connection."
 
-		echo -e "\r${yellow}Set your preferred package mirror? (us,uk,jp)${lsuffix}"
-		read mportmirror
-		/usr/sbin/mport config set mirror_region ${mportmirror}
+			echo -e "\r${yellow}Set your preferred package mirror? (us,uk,jp)${lsuffix}"
+			read mportmirror
+			run_step "Updating the package mirror" \
+			    /usr/sbin/mport config set mirror_region "${mportmirror}"
 
 		# age verifcation is required in some locales, so we ask for it here to ensure the best experience for users in those areas.
 		echo "Jurisdictions with required age verification include California, Colorado, Illinois, and Brazil. Parental controls will be enabled for all users and can be configured with the agectl utility."
 		echo "If you do not live in a region with required age verification, you can disable this feature and the associated parental controls."
-		echo -e "\r${red}MidnightBSD does not support ID checks or AI facial scanning for age verification. You may NOT use MidnightBSD in regions requiring it.${lsuffix}"
-		echo -e "\r${yellow}Do you live in a region with required age verification or want parental controls enabled? (yes or no)${lsuffix}"
-		read ageverify
-		if [ "${ageverify}" = "no" ]; then
-			/usr/sbin/sysrc aged_enable=NO
-		else
-			echo "parental will enable parental controls based on age attestion for apps in the MidnightBSD package manger."
-			echo -e "\r${yellow}Specify one of the following regions for age attestion (US-CA, US-CO, US-IL, BR, parental)${lsuffix}"
-			read ageregion
-			/usr/sbin/agectl -r ${ageregion}
-			echo "You may change the setting later with the agectl -r <region> command."
-		fi
-
-		echo -e "\r${yellow}Would you like to report your install via bsdstats? (yes or no)${lsuffix}"
-		read installbstat
-		if [ "${installbstat}" = "yes" ]; then
-			if [ ! -f /usr/local/etc/rc.d/bsdstats.sh ]; then
-				/sbin/ipfw disable firewall
-				/usr/sbin/mport install bsdstats
-				/sbin/ipfw enable firewall
-			fi
-			/usr/sbin/sysrc bsdstats_enable=YES
-		fi
-
-		echo -e "\r${yellow}Would you like to report your install via hw-probe? (yes or no)${lsuffix}"
-		read installhp
-		if [ ${installhp} = "yes" ]; then
-			if [ ! -f /usr/local/bin/hw-probe ]; then
-				/sbin/ipfw disable firewall
-				/usr/sbin/mport install hw-probe
-				/sbin/ipfw enable firewall
-			fi
-			echo "Scanning and uploading... (one-time event)"
-			/usr/local/bin/hw-probe -upload -all
-		fi
-
-		if [ `uname -m` == 'amd64' ]; then
-			echo -e "\r${yellow}Would you like to install Ravenports, an alternative package manager? (yes or no)${lsuffix}"
-                	read ravenports
-                	if [ ${ravenports} = "yes" ]; then
-				/usr/bin/fetch http://www.ravenports.com/repository/ravenports-downloader.sh -o - | /bin/sh
-				sysrc local_startup+="/raven/etc/rc.d"
-
-				echo "You can now use Ravenports or mports to install software on this system."
-				echo "Consult http://www.ravenports.com/catalog/ for a list of available software for Ravenports."
-			fi
-		fi
-
-		echo -e "\r${yellow}Do you wish to enable a graphical environment? (yes or no)${lsuffix}"
-		read installgui
-
-		if [ ${installgui} = "yes" ]; then
-			echo -e "\r${red}Installing Graphical User Interface${lsuffix}"
-#			xfce/mlogind
-				/sbin/ipfw disable firewall
-				/usr/sbin/mport install midnightbsd-desktop
-				/sbin/ipfw enable firewall
-				/usr/sbin/sysrc mlogind_enable=YES
-				/usr/sbin/sysrc dbus_enable=YES
-
-			echo "The following options will help you install GPU drivers. You may need to perform further x.org configuration to make them work properly"
-
-			if [ -f /usr/local/bin/xconfig ]; then
-				echo "Attempting xconfig configuration.  You can run the utility again by typing xconfig to change settings."
-				/usr/local/bin/xconfig auto
+			echo -e "\r${red}MidnightBSD does not support ID checks or AI facial scanning for age verification. You may NOT use MidnightBSD in regions requiring it.${lsuffix}"
+			echo -e "\r${yellow}Do you live in a region with required age verification or want parental controls enabled? (yes or no)${lsuffix}"
+			read ageverify
+			if [ "${ageverify}" = "no" ]; then
+				run_step "Disabling aged" /usr/sbin/sysrc aged_enable=NO
 			else
-			echo -e "\r${yellow}Do you wish to install Intel or AMD GPU drivers? (yes or no)${lsuffix}"
-			read drmkmod
-			if [ ${drmkmod} = "yes" ]; then
-				/usr/sbin/mport install drm-510-kmod
-				echo -e "\r${yellow}Which GPU module do you want to activate? (amd, radeonkms or intel)${lsuffix}"
-				read kmsmodule
-				if [ ${kmsmodule} = "intel" ]; then
-					/usr/sbin/sysrc kld_list="/boot/modules/i915kms.ko"
-				elif [ ${kmsmodule} = "amd" ]; then
-					/usr/sbin/sysrc kld_list="amdgpu"
-				else 
-					/usr/sbin/sysrc kld_list="/boot/modules/radeonkms.ko"
+				echo "parental will enable parental controls based on age attestion for apps in the MidnightBSD package manger."
+				echo -e "\r${yellow}Specify one of the following regions for age attestion (US-CA, US-CO, US-IL, BR, parental)${lsuffix}"
+				read ageregion
+				run_step "Configuring the age verification region" \
+				    /usr/sbin/agectl -r "${ageregion}"
+				echo "You may change the setting later with the agectl -r <region> command."
+			fi
+
+			echo -e "\r${yellow}Would you like to report your install via bsdstats? (yes or no)${lsuffix}"
+			read installbstat
+			if [ "${installbstat}" = "yes" ]; then
+				if [ ! -f /usr/local/etc/rc.d/bsdstats.sh ]; then
+					install_pkg bsdstats
+				fi
+				run_step "Enabling bsdstats" /usr/sbin/sysrc bsdstats_enable=YES
+			fi
+
+			echo -e "\r${yellow}Would you like to report your install via hw-probe? (yes or no)${lsuffix}"
+			read installhp
+			if [ "${installhp}" = "yes" ]; then
+				if [ ! -f /usr/local/bin/hw-probe ]; then
+					install_pkg hw-probe
+				fi
+				if [ -x /usr/local/bin/hw-probe ]; then
+					echo "Scanning and uploading... (one-time event)"
+					run_step "Running hw-probe" /usr/local/bin/hw-probe -upload -all
+				else
+					warn_msg "hw-probe is not available; skipping the hardware report."
 				fi
 			fi
 
-			echo -e "\r${yellow}Do you wish to install nvidia GPU driver? (no, 340, 390, 470)${lsuffix}"
-			read nvidia
-			if [ ${nvidia} = "340" ]; then
-				/usr/sbin/mport install nvidia-driver-340
-				/usr/sbin/sysrc kld_list="nvidia"
-			elif [ ${nvidia} = "390" ]; then
-				/usr/sbin/mport install nvidia-driver-390
-				/usr/sbin/sysrc kld_list="nvidia"
-			elif [ $[nvidia} = "470" ]; then
-				/usr/sbin/mport install nvidia-driver-470
-				/usr/sbin/sysrc kld_list="nvidia"
+			if [ "$(uname -m)" = "amd64" ]; then
+				echo -e "\r${yellow}Would you like to install Ravenports, an alternative package manager? (yes or no)${lsuffix}"
+	                	read ravenports
+	                	if [ "${ravenports}" = "yes" ]; then
+					if ! /usr/bin/fetch http://www.ravenports.com/repository/ravenports-downloader.sh -o - | /bin/sh; then
+						warn_msg "Ravenports installation failed."
+					else
+						run_step "Updating local_startup for Ravenports" \
+						    /usr/sbin/sysrc local_startup+="/raven/etc/rc.d"
+
+						echo "You can now use Ravenports or mports to install software on this system."
+						echo "Consult http://www.ravenports.com/catalog/ for a list of available software for Ravenports."
+					fi
+				fi
 			fi
-			echo "Please restart to enable graphical login."
-			echo -e "\r${yellow}Done.${lsuffix}"
+
+			echo -e "\r${yellow}Do you wish to enable a graphical environment? (yes or no)${lsuffix}"
+			read installgui
+
+			if [ "${installgui}" = "yes" ]; then
+				echo -e "\r${red}Installing Graphical User Interface${lsuffix}"
+	#			xfce/mlogind
+					if install_pkg midnightbsd-desktop; then
+						run_step "Enabling mlogind" /usr/sbin/sysrc mlogind_enable=YES
+						run_step "Enabling dbus" /usr/sbin/sysrc dbus_enable=YES
+					else
+						warn_msg "Graphical desktop installation failed; continuing with the rest of firstboot."
+					fi
+
+				echo "The following options will help you install GPU drivers. You may need to perform further x.org configuration to make them work properly"
+
+				if [ -f /usr/local/bin/xconfig ]; then
+					echo "Attempting xconfig configuration.  You can run the utility again by typing xconfig to change settings."
+					run_step "Running xconfig auto" /usr/local/bin/xconfig auto
+				else
+				echo -e "\r${yellow}Do you wish to install Intel or AMD GPU drivers? (yes or no)${lsuffix}"
+				read drmkmod
+				if [ "${drmkmod}" = "yes" ]; then
+					install_pkg drm-510-kmod
+					echo -e "\r${yellow}Which GPU module do you want to activate? (amd, radeonkms or intel)${lsuffix}"
+					read kmsmodule
+					if [ "${kmsmodule}" = "intel" ]; then
+						run_step "Configuring the Intel DRM module" \
+						    /usr/sbin/sysrc kld_list="/boot/modules/i915kms.ko"
+					elif [ "${kmsmodule}" = "amd" ]; then
+						run_step "Configuring the AMD DRM module" \
+						    /usr/sbin/sysrc kld_list="amdgpu"
+					elif [ "${kmsmodule}" = "radeonkms" ]; then
+						run_step "Configuring the Radeon DRM module" \
+						    /usr/sbin/sysrc kld_list="/boot/modules/radeonkms.ko"
+					else
+						warn_msg "Unknown DRM module selection '${kmsmodule}'; skipping DRM module activation."
+					fi
+				fi
+
+				echo -e "\r${yellow}Do you wish to install nvidia GPU driver? (no, 340, 390, 470, 580)${lsuffix}"
+				read nvidia
+				if [ "${nvidia}" = "340" ]; then
+					if install_pkg nvidia-driver-340; then
+						run_step "Configuring the NVIDIA module" \
+						    /usr/sbin/sysrc kld_list="nvidia"
+					fi
+				elif [ "${nvidia}" = "390" ]; then
+					if install_pkg nvidia-driver-390; then
+						run_step "Configuring the NVIDIA module" \
+						    /usr/sbin/sysrc kld_list="nvidia"
+					fi
+				elif [ "${nvidia}" = "470" ]; then
+					if install_pkg nvidia-driver-470; then
+						run_step "Configuring the NVIDIA module" \
+						    /usr/sbin/sysrc kld_list="nvidia"
+					fi
+				elif [ "${nvidia}" = "580" ]; then
+					if install_pkg nvidia-driver; then
+						run_step "Configuring the NVIDIA module" \
+						    /usr/sbin/sysrc kld_list="nvidia"
+					fi
+				elif [ "${nvidia}" != "no" ]; then
+					warn_msg "Unknown NVIDIA driver selection '${nvidia}'; skipping NVIDIA driver installation."
+				fi
+				echo "Please restart to enable graphical login."
+				echo -e "\r${yellow}Done.${lsuffix}"
 			fi
 		else
 			echo "To run this utility again, rm ${receipt} and restart."
 		fi
-		touch ${receipt}
-	fi
-}
+			run_step "Creating the firstboot receipt" touch "${receipt}"
+		fi
+	}
 
 load_rc_config $name
 run_rc_command "$1"
