Seventh import of some freebsd 13-stable features from Oct 28

diff --git a/libexec/rc/rc.d/nfsd b/libexec/rc/rc.d/nfsd
--- a/libexec/rc/rc.d/nfsd
+++ b/libexec/rc/rc.d/nfsd
@@ -4,7 +4,7 @@
 
 # PROVIDE: nfsd
 # REQUIRE: mountcritremote mountd hostname gssd nfsuserd
-# KEYWORD: nojail shutdown
+# KEYWORD: nojailvnet shutdown
 
 . /etc/rc.subr
 
@@ -26,6 +26,12 @@ nfsd_precmd()
 	# Load the modules now, so that the vfs.nfsd sysctl
 	# oids are available.
 	load_kld nfsd || return 1
+
+	if [ -n "${nfs_server_maxio}" ] && ! check_jail jailed; then
+		if ! sysctl vfs.nfsd.srvmaxio=${nfs_server_maxio} >/dev/null; then
+			warn "Failed to set server max I/O"
+		fi
+	fi
 
 	if checkyesno nfs_reserved_port_only; then
 		echo 'NFS on reserved port only=YES'
